import { type Question } from './types'

export const SAMPLE_QUESTIONS: Question[] = [
  // Easy (1-5)
  {
    id: 'q1',
    category: 'General Knowledge',
    difficulty: 'easy',
    prompt: 'Which planet is known as the Red Planet?',
    choices: ['Mercury', 'Venus', 'Earth', 'Mars'],
    correctIndex: 3,
  },
  {
    id: 'q2',
    category: 'Science',
    difficulty: 'easy',
    prompt: 'What is H2O commonly known as?',
    choices: ['Salt', 'Water', 'Oxygen', 'Hydrogen'],
    correctIndex: 1,
  },
  {
    id: 'q3',
    category: 'Geography',
    difficulty: 'easy',
    prompt: 'What is the capital of France?',
    choices: ['Madrid', 'Berlin', 'Paris', 'Rome'],
    correctIndex: 2,
  },
  {
    id: 'q4',
    category: 'Movies',
    difficulty: 'easy',
    prompt: 'Who directed the movie "Jurassic Park"?',
    choices: ['James Cameron', 'Steven Spielberg', 'Christopher Nolan', 'Ridley Scott'],
    correctIndex: 1,
  },
  {
    id: 'q5',
    category: 'Sports',
    difficulty: 'easy',
    prompt: 'How many players are on a standard soccer team on the field?',
    choices: ['9', '10', '11', '12'],
    correctIndex: 2,
  },
  // Medium (6-10)
  {
    id: 'q6',
    category: 'History',
    difficulty: 'medium',
    prompt: 'In which year did the Berlin Wall fall?',
    choices: ['1987', '1989', '1991', '1993'],
    correctIndex: 1,
  },
  {
    id: 'q7',
    category: 'Science',
    difficulty: 'medium',
    prompt: 'What particle is exchanged to mediate the electromagnetic force?',
    choices: ['Gluon', 'W boson', 'Z boson', 'Photon'],
    correctIndex: 3,
  },
  {
    id: 'q8',
    category: 'Geography',
    difficulty: 'medium',
    prompt: 'Which river flows through the city of Budapest?',
    choices: ['Danube', 'Rhine', 'Seine', 'Thames'],
    correctIndex: 0,
  },
  {
    id: 'q9',
    category: 'Music',
    difficulty: 'medium',
    prompt: 'Which composer wrote the opera "The Magic Flute"?',
    choices: ['Mozart', 'Beethoven', 'Verdi', 'Wagner'],
    correctIndex: 0,
  },
  {
    id: 'q10',
    category: 'Technology',
    difficulty: 'medium',
    prompt: 'What does the acronym RAID stand for in computing?',
    choices: [
      'Redundant Array of Independent Disks',
      'Random Access Integrated Data',
      'Rapid Application Interface Design',
      'Remote Access Internet Device',
    ],
    correctIndex: 0,
  },
  // Hard (11-15)
  {
    id: 'q11',
    category: 'Physics',
    difficulty: 'hard',
    prompt: 'Which equation describes the behavior of quantum mechanical systems?',
    choices: ['Navier–Stokes', 'Schrödinger equation', 'Maxwell’s equations', 'Dirac delta'],
    correctIndex: 1,
  },
  {
    id: 'q12',
    category: 'Literature',
    difficulty: 'hard',
    prompt: 'Who wrote "One Hundred Years of Solitude"?',
    choices: ['Isabel Allende', 'Gabriel García Márquez', 'Jorge Luis Borges', 'Mario Vargas Llosa'],
    correctIndex: 1,
  },
  {
    id: 'q13',
    category: 'Mathematics',
    difficulty: 'hard',
    prompt: 'What is the smallest non-abelian simple group?',
    choices: ['A5', 'S4', 'Z7', 'D8'],
    correctIndex: 0,
  },
  {
    id: 'q14',
    category: 'Chemistry',
    difficulty: 'hard',
    prompt: 'Which concept explains the delocalization of electrons in benzene?',
    choices: ['Hyperconjugation', 'Resonance', 'Inductive effect', 'Back bonding'],
    correctIndex: 1,
  },
  {
    id: 'q15',
    category: 'World History',
    difficulty: 'hard',
    prompt: 'The Treaty of Westphalia in 1648 ended which conflict?',
    choices: ['Hundred Years’ War', 'Thirty Years’ War', 'War of the Roses', 'Seven Years’ War'],
    correctIndex: 1,
  },
]
